instagram/accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView

from .views import register_view, UserDetailView, UserPersonalInfoChangeView, subscribe_to_user

app_name = 'accounts'

urlpatterns = [
    path('login', LoginView.as_view(), name='login'),
    path('logout', LogoutView.as_view(), name='logout'),
    path('create/', register_view, name='create'),
    path('<int:pk>', UserDetailView.as_view(), name='user_detail'),
    path('<int:pk>/update', UserPersonalInfoChangeView.as_view(), name='user_update'),
    path('<int:pk>/subscribe', subscribe_to_user, name='subscribe_to_user'),
]

instagram/instagram/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('', include('webapp.urls', namespace='webapp'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

instagram/webapp/urls.py
from django.urls import path

from .views import *

app_name = 'webapp'

urlpatterns = [
    path('', post_views.IndexView.as_view(), name='index'),
    path('posts/<int:pk>', post_views.PostDetailView.as_view(), name='post_detail'),
    path('posts/create', post_views.PostCreateView.as_view(), name='post_create'),
    path('posts/<int:pk>/comment_create', comment_views.CommentCreateView.as_view(), name='comment_create'),
    path('posts/<int:pk>/like', post_views.put_likes, name='put_likes'),
    path('search', search_views.SearchView.as_view(), name='search')
]

instagram/webapp/models.py
from django.conf import settings
from django.contrib.auth.models import User
from django.db.models import ImageField
from django.db import models


class Post(models.Model):
    picture = ImageField(
        null=True,
        blank=True,
        upload_to='user_pics',
        verbose_name='Picture'
    )

    description = models.TextField(
        max_length=200,
        null=True,
        blank=True,
        verbose_name='Description',
    )

    author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        related_name='pictures',
        on_delete=models.PROTECT,
    )

    created_at = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Add time')

    users_like = models.ManyToManyField(
        User,
        related_name='liked_posts',
        blank=True
    )


class Comment(models.Model):
    post = models.ForeignKey(
        'webapp.Post',
        related_name='comments',
        on_delete=models.CASCADE,
        verbose_name='Post'
    )

    author = models.CharField(
        max_length=20,
        null=False,
        blank=False,
        verbose_name='Author'
    )

    text = models.TextField(
        max_length=1000,
        null=False,
        blank=False,
        verbose_name='Text'
    )

    created_at = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Add time'
    )

    def __str__(self):
        return self.text[:20]

instagram/webapp/forms.py
from django import forms
from django.forms import widgets

from webapp.models import Post, Comment


class PostForm(forms.ModelForm):
    picture = forms.ImageField(
        required=True
    )

    class Meta:
        model = Post
        fields = ['picture', 'description']


class CommentForm(forms.ModelForm):
    text = forms.CharField(
        required=True,
        max_length=1000,
        widget=widgets.Textarea
    )

    class Meta:
        model = Comment
        fields = ['text']


class SearchForm(forms.Form):
    search = forms.CharField(
        required=True,
        max_length=50,
    )

instagram/webapp/views/comment_views.py
from django.shortcuts import redirect
from django.urls import reverse
from django.views.generic import CreateView

from webapp.forms import CommentForm
from webapp.models import Post, Comment


class CommentCreateView(CreateView):
    form_class = CommentForm

    def form_valid(self, form):
        post = Post.objects.get(pk=self.kwargs.get('pk'))

        form.instance.post = post
        form.instance.author = self.request.user
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('webapp:post_detail', kwargs={'pk': self.kwargs.get('pk')})

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return redirect('accounts:login')
        return super().dispatch(request, *args, **kwargs)

instagram/webapp/views/post_views.py
from django.contrib.auth.models import User
from django.shortcuts import redirect, get_object_or_404
from django.urls import reverse
from django.views.generic import ListView, DetailView, CreateView

from webapp.forms import PostForm, CommentForm, SearchForm
from webapp.models import Post


class IndexView(ListView):
    template_name = 'posts/index.html'
    context_object_name = 'posts'

    def get_queryset(self):
        return Post.objects.all().order_by('-created_at')

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['search_form'] = SearchForm
        context['form'] = CommentForm
        return context

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return redirect('accounts:login')
        return super().dispatch(request, *args, **kwargs)


class PostDetailView(DetailView):
    model = Post
    template_name = 'posts/detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['comments'] = self.object.comments.all().order_by('-created_at')
        context['form'] = CommentForm
        context['likes'] = len(self.object.users_like.all())

        return context


class PostCreateView(CreateView):
    template_name = 'posts/post_create.html'
    model = Post
    form_class = PostForm

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('webapp:post_detail', kwargs={'pk': self.object.pk})

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return redirect('accounts:login')
        return super().dispatch(request, *args, **kwargs)


def put_likes(request, **kwargs):
    user = request.user
    post = Post.objects.get(pk=kwargs['pk'])

    if user in post.users_like.all():
        post.users_like.remove(user)
    else:
        post.users_like.add(user)

    return redirect(request.META.get('HTTP_REFERER'))

instagram/webapp/views/search_views.py
from django.contrib.auth.models import User
from django.views.generic import TemplateView

from webapp.forms import SearchForm


class SearchView(TemplateView):
    template_name = 'search.html'

    def get_context_data(self, *args, **kwargs):
        form = SearchForm
        context = super().get_context_data(**kwargs)
        query = self.request.GET.get('search')
        if query:
            results = set()

            search_username = User.objects.filter(username__icontains=query)
            for user in search_username:
                results.add(user)

            search_email = User.objects.filter(email__icontains=query)
            for user in search_email:
                results.add(user)

            search_name = User.objects.filter(first_name__icontains=query)
            for user in search_name:
                results.add(user)

            search_about_me = User.objects.filter(profile__about_me__icontains=query)
            for user in search_about_me:
                results.add(user)

            context['results'] = results

        context['search_form'] = form
        return context

instagram/webapp/templates/posts/detail.html
{% extends "base_webapp.html" %}
{% load staticfiles %}
{% block content %}
<div class="d-flex justify-content-center">
<div class="card mb-3" style="width: 900px;">
  <div class="row no-gutters">
    <div class="col-md-8">
      <img src="{{ post.picture.url }}" class="card-img" alt="image" style="width:100%;">
    </div>
    <div class="col-md-4">
      <div class="card-body">
        <a href="{% url 'accounts:user_detail' post.author.pk %}">
          <h5 class="card-title"><b>{{ post.author }}</b></h5>
        </a>
        <hr>
        <p class="card-text">
            <b>
            <a href="{% url 'accounts:user_detail' post.author.pk %}">
                {{ post.author }}
            </a>
        </b>
            {{ post.description }}
        </p>
        {% for comment in comments %}
          <p class="card-text"><b>{{ comment.author }}</b> {{ comment.text }}</p>
        {% endfor %}
        <hr>
      <div>
        <a href="{% url 'webapp:put_likes' post.pk %}">
            {% if request.user in post.users_like.all %}
                <img src="{% static 'like.png' %}" alt="like" style="width:25px;">
            {% else %}
                <img src="{% static 'heart.png' %}" alt="like" style="width:25px;">
            {% endif %}
        </a>
        {% if post.users_like.all.count > 0 %}
        <div>
          <b> {{ post.users_like.all.count }} отметок "Нравится"</b>
        </div>
        <hr>
        {% endif %}
      </div>
        {% if user.is_authenticated %}
        <form action="{% url 'webapp:comment_create' post.pk %}" method="post">
          {% include 'partial/comment_form.html' %}
        </form>
        {% endif %}
      </div>
    </div>
  </div>
</div>
</div>
{% endblock %}

instagram/webapp/templates/posts/index.html
{% extends "base_webapp.html" %}
{% load staticfiles %}

{% block search %}
<form action="{% url 'webapp:search' %}" method="get">
    {% include 'partial/search_form.html' %}
</form>
{% endblock %}

{% block content %}
{% for post in posts %}
<div class="content d-flex justify-content-center">
    <div class="card mb-5" style="width: 40rem;">
      <div class="card-body d-flex justify-content-between p-2">
          <a href="{% url 'accounts:user_detail' post.author.pk %}">
              <img src="{{ post.author.profile.avatar.url }}" alt="" style="width:50px; border-radius:50%;">
              <b>{{ post.author }}</b>
          </a>
          <a href="{% url 'webapp:post_detail' post.pk %}" style="font-size:17px; font-weight: 700;">...</a>
      </div>
          <img src="{{ post.picture.url }}" class="card-img-top" alt="{% static '733614.svg' %}">
      <div class="card-body">
      <div>
        <a href="{% url 'webapp:put_likes' post.pk %}">
            {% if request.user in post.users_like.all %}
                <img src="{% static 'like.png' %}" alt="like" style="width:25px;">
            {% else %}
                <img src="{% static 'heart.png' %}" alt="like" style="width:25px;">
            {% endif %}
        </a>
          <a href="{% url 'webapp:post_detail' post.pk %}" class="ml-2">
              <img src="{% static 'comment.png' %}" alt="comments" style="width:25px;">
          </a>
        {% if post.users_like.all.count > 0 %}
        <div>
          <b> {{ post.users_like.all.count }} отметок "Нравится"</b>
        </div>
        {% endif %}
      </div>
          <p class="card-text mb-1">
              <b><a href="{% url 'accounts:user_detail' post.author.pk %}">{{ post.author }}</a></b> {{post.description }}
          </p>
          {% if post.comments.all.count > 1 %}
          <a href="{% url 'webapp:post_detail' post.pk %}" style="color: grey;">
              Посмотреть все комментарии ({{ post.comments.all.count }})
          </a>
          {% endif %}
          <p class="card-text"><b>{{ post.comments.last.author }}</b> {{ post.comments.last.text }}</p>
        {% if user.is_authenticated %}
        <form action="{% url 'webapp:comment_create' post.pk %}" method="post">
          {% include 'partial/comment_form.html' %}
        </form>
        {% endif %}
      </div>
    </div>
</div>
{% endfor %}
{% endblock %}

instagram/webapp/templates/posts/post_create.html
{% extends "base_webapp.html" %}

{% block content %}
<h1>Create new post</h1>

<form action="{% url 'webapp:post_create' %}" method="post" enctype="multipart/form-data">
    {% include 'partial/form.html' %}
</form>
{% endblock %}