instagram/accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView

from .views import register_view, UserDetailView, UserPersonalInfoChangeView, subscribe_to_user

app_name = 'accounts'

urlpatterns = [
    path('login', LoginView.as_view(), name='login'),
    path('logout', LogoutView.as_view(), name='logout'),
    path('create/', register_view, name='create'),
    path('<int:pk>', UserDetailView.as_view(), name='user_detail'),
    path('<int:pk>/update', UserPersonalInfoChangeView.as_view(), name='user_update'),
    path('<int:pk>/subscribe', subscribe_to_user, name='subscribe_to_user'),
]

instagram/instagram/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('', include('webapp.urls', namespace='webapp'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

instagram/webapp/urls.py
from django.urls import path

from .views import *

app_name = 'webapp'

urlpatterns = [
    path('', post_views.IndexView.as_view(), name='index'),
    path('posts/<int:pk>', post_views.PostDetailView.as_view(), name='post_detail'),
    path('posts/create', post_views.PostCreateView.as_view(), name='post_create'),
    path('posts/<int:pk>/comment_create', comment_views.CommentCreateView.as_view(), name='comment_create'),
    path('posts/<int:pk>/like', post_views.put_likes, name='put_likes'),
    path('search', search_views.SearchView.as_view(), name='search')
]

instagram/accounts/models.py
from django.db import models
from django.contrib.auth.models import User


class Profile(models.Model):
    user = models.OneToOneField(
        User,
        related_name='profile',
        on_delete=models.CASCADE,
        verbose_name='User'
    )

    avatar = models.ImageField(
        null=False,
        blank=False,
        upload_to='user_pics',
        verbose_name='Avatar'
    )

    about_me = models.TextField(
        null=True,
        blank=True,
        max_length=1000,
        verbose_name='About me'
    )

    phone_number = models.CharField(
        max_length=12,
        null=True,
        blank=True,
        verbose_name='Phone number'
    )

    gender = models.CharField(
        null=True,
        blank=True,
        verbose_name='Gender',
        max_length=10,
    )

    subscribe_to = models.ManyToManyField(
        'accounts.Profile',
        related_name='subscriber',
        blank=True
    )

    def __str__(self):
        return self.user.get_full_name() + "'s Profile"

    class Meta:
        verbose_name = 'Profile'
        verbose_name_plural = 'Profiles'

instagram/accounts/forms.py
from django.contrib.auth.models import User
from django import forms
from django.db.transaction import commit
from django.forms import widgets

from accounts.models import Profile


class UserCreationForm(forms.ModelForm):
    password = forms.CharField(
        strip=False,
        widget=forms.PasswordInput
    )

    password_confirm = forms.CharField(
        widget=forms.PasswordInput,
        strip=False
    )

    def clean_password_confirm(self):
        password = self.cleaned_data.get("password")
        password_confirm = self.cleaned_data.get("password_confirm")
        if password and password_confirm and password != password_confirm:
            raise forms.ValidationError('Password do not confirm')
        return password_confirm

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password"])
        if commit:
            user.save()
        return user

    class Meta:
        model = User
        fields = ['username', 'password', 'password_confirm', 'email']


class UserChangeForm(forms.ModelForm):
    avatar = forms.ImageField(
        required=True
    )

    about_me = forms.CharField(
        required=False,
        widget=widgets.Textarea,
        max_length=1000
    )

    phone_number = forms.CharField(
        required=False,
        max_length=12,
    )

    gender = forms.ChoiceField(
        required=False,
        choices=(('male', 'male'), ('female', 'female'))
    )

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email']
        profile_fields = ['avatar', 'phone_number', 'about_me', 'gender']

    def save(self):
        user = super().save(commit)
        self.save_profile(commit)
        return user

    def save_profile(self, commit=True):
        try:
            profile = self.instance.profile
        except Profile.DoesNotExist:
            profile = Profile.objects.create(user=self.instance)

        for field in self.Meta.profile_fields:
            setattr(profile, field, self.cleaned_data[field])

        if not profile.avatar:
            profile.avatar = None

        if commit:
            profile.save()

    def get_initial_for_field(self, field, field_name):
        if field_name in self.Meta.profile_fields:
            try:
                return getattr(self.instance.profile, field_name)
            except Profile.DoesNotExist:
                return None

        return super().get_initial_for_field(field, field_name)

instagram/accounts/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.mixins import UserPassesTestMixin
from django.contrib.auth.models import User
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views.generic import DetailView, UpdateView

from accounts.forms import UserCreationForm, UserChangeForm
from accounts.models import Profile
from webapp.models import Post


def register_view(request, *args, **kwargs):
    if request.method == 'POST':
        form = UserCreationForm(data=request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('webapp:index')
    else:
        form = UserCreationForm()
    return render(request, 'create_user.html', context={'form': form})


class UserDetailView(DetailView):
    model = User
    template_name = 'user_detail.html'
    context_object_name = 'user_obj'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['posts'] = self.object.pictures.all()
        context['subscribers'] = len(self.object.profile.subscriber.all())
        context['subscribe_to'] = len(self.object.profile.subscribe_to.all())

        return context


class UserPersonalInfoChangeView(UserPassesTestMixin, UpdateView):
    model = User
    template_name = 'user_info_change.html'
    form_class = UserChangeForm
    context_object_name = 'user_obj'

    def get_success_url(self):
        return reverse('accounts:user_detail', kwargs={'pk': self.object.pk})

    def test_func(self):
        return self.request.user.pk == self.kwargs['pk']


def subscribe_to_user(request, **kwargs):
    subscriber_profile = Profile.objects.get(user=request.user.pk)
    user_profile = Profile.objects.get(user=kwargs['pk'])

    if subscriber_profile in user_profile.subscriber.all():
        subscriber_profile.subscribe_to.remove(user_profile)
    else:
        subscriber_profile.subscribe_to.add(user_profile)

    return redirect(request.META.get('HTTP_REFERER'))

instagram/accounts/templates/base_accounts.html
<!doctype html>
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>instagram</title>
    <link rel="stylesheet" href="{% static 'css/reset.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
    <div class="container">
        {% block content %}{% endblock %}
    </div>
    <script src="../static/js/jquery-3.4.1.min.js"></script>
    <script src="../static/js/bootstrap.min.js"></script>
</body>
</html>

instagram/accounts/templates/create_user.html
{% extends "base_accounts.html" %}

{% load staticfiles %}

{% block content %}
<div class="d-flex align-items-center flex-column">
    <div class="card mt-5 align-items-center" style="width: 25rem;">
  <img src="{% static 'Instagram_logo.svg.png' %}" class="card-img-top" style="width: 18rem;" alt="...">
  <div class="card-body">
    <form action="{% url 'accounts:create' %}" method="post">
        <div class="text-center">
        {% csrf_token %}
        {% for error in form.non_field_errors %}
            <p class="form-error">{{ error }}</p>
        {% endfor %}

        {% for field in form %}
            <div class="form-group">
                <label for="{{ field.id_for_label }}" class="form-label
            {% if field.field.required %}required{% endif %}">{{ field.label }}</label>
                {% if field.errors %}
                    {{ field }}
                    {% for error in field.errors %}
                        <p class="form-error">{{ error }}</p>
                    {% endfor %}
                {% else %}
                    {{ field }}
                {% endif %}
            </div>
        {% endfor %}
        <button type="submit" class="btn btn-primary">Зарегистрироваться</button>
        </div>
    </form>
  </div>
</div>

</div>


{% endblock %}

instagram/accounts/templates/user_detail.html
{% extends "base_webapp.html" %}
{% load staticfiles %}


{% block content %}

    <div class="row">
        <div class="avatar col-md-4 text-center">
            <img src="{{ user_obj.profile.avatar.url }}" alt="avatar" class="avatar_img">
        </div>
        <div class="user_info d-flex flex-column col-md-8 justify-content-center">
            <div class="d-flex">
                <h4>{{ user_obj.username }}</h4>
                {% if user.pk == user_obj.pk %}
                    <a href="{% url 'accounts:user_update' user.pk %}" style="border: 1px solid #efefef;" class="p-1 ml-2">
                        Редактировать профиль
                    </a>
                    <a href="{% url 'accounts:logout' %}" class="ml-4 mt-1">
                        <img src="{% static 'logout.png' %}" alt="logout" style="width:25px;">
                    </a>
                {% else %}
                    <a href="{% url 'accounts:subscribe_to_user' user_obj.pk %}"style="border: 1px solid #efefef;" class="p-1 ml-2">
                        Подписаться
                    </a>
                {% endif %}
            </div>
            <div class="">
                <span class="mr-4"><b>{{ user_obj.pictures.all.count }}</b> публикации</span>
                <span class="mr-4"><b>{{ subscribers }}</b> подписчиков</span>
                <span class="mr-4">Подписки: <b>{{ subscribe_to }}</b></span>
            </div>
            <div class="">
                {{ user_obj.first_name }} {{ user_obj.last_name }}
            </div>
            <div>
                {{ user_obj.profile.about_me }}
            </div>
        </div>
    </div>
    <hr>
    <div class="row mt-5">
        {% for post in posts %}
        <div class="col-md-4">
            <a href="{% url 'webapp:post_detail' post.pk %}"><img src="{{ post.picture.url }}" alt="image" style="width: 100%;"></a>
        </div>
        {% endfor %}
    </div>

{% endblock %}

instagram/accounts/templates/user_info_change.html
{% extends 'base_webapp.html' %}

{% block title %}Личный кабинет{% endblock %}

{% block content %}
    <h1>Личный кабинет</h1>
    <form action="{% url 'accounts:user_update' user.pk %}" method="post" enctype="multipart/form-data">
        {% include 'partial/form.html' %}
    </form>
{% endblock %}