instagram/accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView

from .views import register_view, UserDetailView, UserPersonalInfoChangeView, subscribe_to_user

app_name = 'accounts'

urlpatterns = [
    path('login', LoginView.as_view(), name='login'),
    path('logout', LogoutView.as_view(), name='logout'),
    path('create/', register_view, name='create'),
    path('<int:pk>', UserDetailView.as_view(), name='user_detail'),
    path('<int:pk>/update', UserPersonalInfoChangeView.as_view(), name='user_update'),
    path('<int:pk>/subscribe', subscribe_to_user, name='subscribe_to_user'),
]

instagram/instagram/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('', include('webapp.urls', namespace='webapp'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

instagram/webapp/urls.py
from django.urls import path

from .views import *

app_name = 'webapp'

urlpatterns = [
    path('', post_views.IndexView.as_view(), name='index'),
    path('posts/<int:pk>', post_views.PostDetailView.as_view(), name='post_detail'),
    path('posts/create', post_views.PostCreateView.as_view(), name='post_create'),
    path('posts/<int:pk>/comment_create', comment_views.CommentCreateView.as_view(), name='comment_create'),
    path('posts/<int:pk>/like', post_views.put_likes, name='put_likes'),
    path('search', search_views.SearchView.as_view(), name='search')
]

instagram/webapp/models.py
from django.conf import settings
from django.contrib.auth.models import User
from django.db.models import ImageField
from django.db import models


class Post(models.Model):
    picture = ImageField(
        null=True,
        blank=True,
        upload_to='user_pics',
        verbose_name='Picture'
    )

    description = models.TextField(
        max_length=200,
        null=True,
        blank=True,
        verbose_name='Description',
    )

    author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        related_name='pictures',
        on_delete=models.PROTECT,
    )

    created_at = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Add time')

    users_like = models.ManyToManyField(
        User,
        related_name='liked_posts',
        blank=True
    )


class Comment(models.Model):
    post = models.ForeignKey(
        'webapp.Post',
        related_name='comments',
        on_delete=models.CASCADE,
        verbose_name='Post'
    )

    author = models.CharField(
        max_length=20,
        null=False,
        blank=False,
        verbose_name='Author'
    )

    text = models.TextField(
        max_length=1000,
        null=False,
        blank=False,
        verbose_name='Text'
    )

    created_at = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Add time'
    )

    def __str__(self):
        return self.text[:20]

instagram/webapp/forms.py
from django import forms
from django.forms import widgets

from webapp.models import Post, Comment


class PostForm(forms.ModelForm):
    picture = forms.ImageField(
        required=True
    )

    class Meta:
        model = Post
        fields = ['picture', 'description']


class CommentForm(forms.ModelForm):
    text = forms.CharField(
        required=True,
        max_length=1000,
        widget=widgets.Textarea
    )

    class Meta:
        model = Comment
        fields = ['text']


class SearchForm(forms.Form):
    search = forms.CharField(
        required=True,
        max_length=50,
    )

instagram/webapp/views/comment_views.py
from django.shortcuts import redirect
from django.urls import reverse
from django.views.generic import CreateView

from webapp.forms import CommentForm
from webapp.models import Post, Comment


class CommentCreateView(CreateView):
    form_class = CommentForm

    def form_valid(self, form):
        post = Post.objects.get(pk=self.kwargs.get('pk'))

        form.instance.post = post
        form.instance.author = self.request.user
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('webapp:post_detail', kwargs={'pk': self.kwargs.get('pk')})

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return redirect('accounts:login')
        return super().dispatch(request, *args, **kwargs)

instagram/webapp/views/post_views.py
from django.contrib.auth.models import User
from django.shortcuts import redirect, get_object_or_404
from django.urls import reverse
from django.views.generic import ListView, DetailView, CreateView

from webapp.forms import PostForm, CommentForm, SearchForm
from webapp.models import Post


class IndexView(ListView):
    template_name = 'posts/index.html'
    context_object_name = 'posts'

    def get_queryset(self):
        return Post.objects.all().order_by('-created_at')

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['search_form'] = SearchForm
        context['form'] = CommentForm
        return context

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return redirect('accounts:login')
        return super().dispatch(request, *args, **kwargs)


class PostDetailView(DetailView):
    model = Post
    template_name = 'posts/detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['comments'] = self.object.comments.all().order_by('-created_at')
        context['form'] = CommentForm
        context['likes'] = len(self.object.users_like.all())

        return context


class PostCreateView(CreateView):
    template_name = 'posts/post_create.html'
    model = Post
    form_class = PostForm

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('webapp:post_detail', kwargs={'pk': self.object.pk})

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return redirect('accounts:login')
        return super().dispatch(request, *args, **kwargs)


def put_likes(request, **kwargs):
    user = request.user
    post = Post.objects.get(pk=kwargs['pk'])

    if user in post.users_like.all():
        post.users_like.remove(user)
    else:
        post.users_like.add(user)

    return redirect(request.META.get('HTTP_REFERER'))

instagram/webapp/views/search_views.py
from django.contrib.auth.models import User
from django.views.generic import TemplateView

from webapp.forms import SearchForm


class SearchView(TemplateView):
    template_name = 'search.html'

    def get_context_data(self, *args, **kwargs):
        form = SearchForm
        context = super().get_context_data(**kwargs)
        query = self.request.GET.get('search')
        if query:
            results = set()

            search_username = User.objects.filter(username__icontains=query)
            for user in search_username:
                results.add(user)

            search_email = User.objects.filter(email__icontains=query)
            for user in search_email:
                results.add(user)

            search_name = User.objects.filter(first_name__icontains=query)
            for user in search_name:
                results.add(user)

            search_about_me = User.objects.filter(profile__about_me__icontains=query)
            for user in search_about_me:
                results.add(user)

            context['results'] = results

        context['search_form'] = form
        return context

instagram/webapp/templates/base_webapp.html
<!doctype html>
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>instagram</title>
    <link rel="stylesheet" href="{% static 'css/reset.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
    <nav class="navbar mb-5">
        <div class="container">
            <div class="menu_logo">
                <a href="{% url 'webapp:index' %}" class="d-flex">
                    <img src="{% static '733614.svg'%}" alt="logo" class="main_logo">
                    <img src="{% static 'Instagram_logo.svg.png'%}" alt="logo" class="logo_text mt-1">
                </a>
            </div>
            <div>
                {% block search %}{% endblock %}
            </div>
            <div class="menu">
                <ul class="d-flex">
                    {% if user.is_authenticated %}
                    <li>
                        <a href="{% url 'webapp:post_create' %}" class="mr-3">
                            <img src="{% static 'post.png' %}" alt="new post" style="width:25px;">
                        </a>
                    </li>
                    <li>
                        <a href="{% url 'accounts:user_detail' user.pk %}">
                            <img src="{% static 'user.png' %}" alt="profile" style="width:25px;">
                        </a>
                    </li>
                    {% else %}
                    <li><a href="{% url 'accounts:login' %}" class="btn btn-primary">Войти</a></li>
                    <li><a href="{% url 'accounts:create' %}" class=""><b style="color: blue;">Зарегистрироваться</b></a></li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
    <div class="container">
        {% block content %}{% endblock %}
    </div>
    <footer>
        <div class="container">
            <div>
                <p>by Aldik Gooner</p>
            </div>
        </div>
    </footer>
    <script src="../static/js/jquery-3.4.1.min.js"></script>
    <script src="../static/js/bootstrap.min.js"></script>
</body>
</html>
</html>

instagram/webapp/templates/search.html
{% extends "base_webapp.html" %}
{% block search %}
<form action="{% url 'webapp:search' %}" method="get">
    {% include 'partial/search_form.html' %}
</form>
{% endblock %}
{% block content %}
{% for result in results %}
          <div class="card-header d-flex justify-content-between">
              <a href="{% url 'accounts:user_detail' result.pk %}">{{ result.username }}</a>
          </div>
{% endfor %}
{% endblock %}